# Generated by Django 4.0.1 on 2022-06-22 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_cartitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pieces',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='cakes'),
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(max_length=150)),
                ('custom_description', models.CharField(blank=True, max_length=250)),
                ('custom_instructions', models.CharField(blank=True, max_length=400)),
                ('custom_price', models.FloatField()),
                ('custom_image', models.ImageField(upload_to='custom_images/')),
                ('custom_slug', models.SlugField(default='custom-cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
