# Generated by Django 4.0.1 on 2022-06-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_pieces_alter_item_slug_customorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='alt_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='delivery_addrs',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='inst',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
