# Generated by Django 4.0.1 on 2022-06-25 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cartitems_alt_name_cartitems_alt_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='quantity',
            new_name='quantity_in_kg',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
