# Generated by Django 4.0.1 on 2022-06-25 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_rename_quantity_in_kg_cartitems_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomOrder',
            new_name='CustomCakes',
        ),
    ]
