# Generated by Django 4.0.1 on 2022-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customcakes_custom_instructions_custom_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakes',
            name='custom_price',
            field=models.FloatField(default=0),
        ),
    ]
