# Generated by Django 4.0.1 on 2022-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customcakes_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_orders',
            name='custom_total',
            field=models.FloatField(default=0),
        ),
    ]
