# Generated by Django 4.0.1 on 2022-06-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_custom_orders_custom_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=20),
        ),
    ]
