# Generated by Django 4.0.1 on 2022-06-27 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cartitems_options_alter_customcakes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='custom_orders',
            name='custom_delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivery Date'),
        ),
    ]
