# Generated by Django 4.0.1 on 2022-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_custom_orders_quantity_in_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakes',
            name='custom_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
    ]
