# Generated by Django 4.0.1 on 2022-06-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customcakes_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_orders',
            name='quantity_in_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customcakes',
            name='custom_price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
