# Generated by Django 4.0.1 on 2022-07-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_custom_orders_quantity_in_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='alt_name',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='alt_phone',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
    ]
