# Generated by Django 4.0.1 on 2022-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_cartitems_alt_name_remove_cartitems_alt_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='delivery_date',
            field=models.DateTimeField(default=0),
        ),
    ]
