# Generated by Django 4.0.1 on 2022-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_cartitems_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_orders',
            name='custom_alt_name',
        ),
        migrations.RemoveField(
            model_name='custom_orders',
            name='custom_alt_phone',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivery_addrs',
            field=models.CharField(blank=True, max_length=400, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='inst',
            field=models.CharField(blank=True, max_length=400, verbose_name='Instructions'),
        ),
    ]
