# Generated by Django 4.0.1 on 2022-07-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_custom_orders_quantity_in_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='delivery_addrs',
            field=models.CharField(blank=True, max_length=400, verbose_name='Current Delivery Address'),
        ),
        migrations.AlterField(
            model_name='custom_orders',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Current Delivery Address'),
        ),
    ]
